/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CachedResult { 'timestamp' : Time, 'resultData' : string }
export type DeviceId = string;
export interface Job {
  'id' : JobId,
  'status' : JobStatus,
  'completedAt' : [] | [Time],
  'startedAt' : [] | [Time],
  'jobType' : string,
  'submittedAt' : Time,
  'results' : string,
  'error' : [] | [string],
  'deviceId' : [] | [DeviceId],
  'priority' : bigint,
  'qualityPreset' : string,
  'payload' : string,
}
export type JobId = bigint;
export type JobStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'queued' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export type Time = bigint;
export interface _SERVICE {
  'activateFallback' : ActorMethod<[JobId], undefined>,
  'getCachedResult' : ActorMethod<[string], [] | [CachedResult]>,
  'getJobResults' : ActorMethod<[JobId], [] | [string]>,
  'getJobStatus' : ActorMethod<[JobId], [] | [JobStatus]>,
  'getOptimalQuality' : ActorMethod<[DeviceId], string>,
  'getQueuedJobs' : ActorMethod<[], Array<Job>>,
  'predictLagRisk' : ActorMethod<[], bigint>,
  'registerDevice' : ActorMethod<
    [DeviceId, bigint, bigint, bigint, bigint],
    undefined
  >,
  'submitJob' : ActorMethod<[string, string, [] | [DeviceId], string], JobId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];