/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobId = IDL.Nat;
export const Time = IDL.Int;
export const CachedResult = IDL.Record({
  'timestamp' : Time,
  'resultData' : IDL.Text,
});
export const JobStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'queued' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const DeviceId = IDL.Text;
export const Job = IDL.Record({
  'id' : JobId,
  'status' : JobStatus,
  'completedAt' : IDL.Opt(Time),
  'startedAt' : IDL.Opt(Time),
  'jobType' : IDL.Text,
  'submittedAt' : Time,
  'results' : IDL.Text,
  'error' : IDL.Opt(IDL.Text),
  'deviceId' : IDL.Opt(DeviceId),
  'priority' : IDL.Nat,
  'qualityPreset' : IDL.Text,
  'payload' : IDL.Text,
});

export const idlService = IDL.Service({
  'activateFallback' : IDL.Func([JobId], [], []),
  'getCachedResult' : IDL.Func([IDL.Text], [IDL.Opt(CachedResult)], ['query']),
  'getJobResults' : IDL.Func([JobId], [IDL.Opt(IDL.Text)], []),
  'getJobStatus' : IDL.Func([JobId], [IDL.Opt(JobStatus)], []),
  'getOptimalQuality' : IDL.Func([DeviceId], [IDL.Text], ['query']),
  'getQueuedJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'predictLagRisk' : IDL.Func([], [IDL.Nat], ['query']),
  'registerDevice' : IDL.Func(
      [DeviceId, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'submitJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(DeviceId), IDL.Text],
      [JobId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobId = IDL.Nat;
  const Time = IDL.Int;
  const CachedResult = IDL.Record({
    'timestamp' : Time,
    'resultData' : IDL.Text,
  });
  const JobStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'queued' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const DeviceId = IDL.Text;
  const Job = IDL.Record({
    'id' : JobId,
    'status' : JobStatus,
    'completedAt' : IDL.Opt(Time),
    'startedAt' : IDL.Opt(Time),
    'jobType' : IDL.Text,
    'submittedAt' : Time,
    'results' : IDL.Text,
    'error' : IDL.Opt(IDL.Text),
    'deviceId' : IDL.Opt(DeviceId),
    'priority' : IDL.Nat,
    'qualityPreset' : IDL.Text,
    'payload' : IDL.Text,
  });
  
  return IDL.Service({
    'activateFallback' : IDL.Func([JobId], [], []),
    'getCachedResult' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CachedResult)],
        ['query'],
      ),
    'getJobResults' : IDL.Func([JobId], [IDL.Opt(IDL.Text)], []),
    'getJobStatus' : IDL.Func([JobId], [IDL.Opt(JobStatus)], []),
    'getOptimalQuality' : IDL.Func([DeviceId], [IDL.Text], ['query']),
    'getQueuedJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'predictLagRisk' : IDL.Func([], [IDL.Nat], ['query']),
    'registerDevice' : IDL.Func(
        [DeviceId, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'submitJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(DeviceId), IDL.Text],
        [JobId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };