/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type DeviceId = string;
export type JobId = bigint;
export interface Job {
    id: JobId;
    status: JobStatus;
    completedAt?: Time;
    startedAt?: Time;
    jobType: string;
    submittedAt: Time;
    results: string;
    error?: string;
    deviceId?: DeviceId;
    priority: bigint;
    qualityPreset: string;
    payload: string;
}
export type Time = bigint;
export interface CachedResult {
    timestamp: Time;
    resultData: string;
}
export enum JobStatus {
    cancelled = "cancelled",
    completed = "completed",
    queued = "queued",
    processing = "processing",
    failed = "failed"
}
export interface backendInterface {
    activateFallback(_jobId: JobId): Promise<void>;
    getCachedResult(jobHash: string): Promise<CachedResult | null>;
    getJobResults(jobId: JobId): Promise<string | null>;
    getJobStatus(jobId: JobId): Promise<JobStatus | null>;
    getOptimalQuality(_deviceId: DeviceId): Promise<string>;
    getQueuedJobs(): Promise<Array<Job>>;
    predictLagRisk(): Promise<bigint>;
    registerDevice(_deviceId: DeviceId, _cpuCores: bigint, _gpuCores: bigint, _ramGB: bigint, _connectionSpeed: bigint): Promise<void>;
    submitJob(jobType: string, payload: string, deviceId: DeviceId | null, qualityPreset: string): Promise<JobId>;
}
import type { CachedResult as _CachedResult, DeviceId as _DeviceId, Job as _Job, JobId as _JobId, JobStatus as _JobStatus, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async activateFallback(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateFallback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateFallback(arg0);
            return result;
        }
    }
    async getCachedResult(arg0: string): Promise<CachedResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCachedResult(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCachedResult(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobResults(arg0: JobId): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobResults(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobResults(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobStatus(arg0: JobId): Promise<JobStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobStatus(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobStatus(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOptimalQuality(arg0: DeviceId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getOptimalQuality(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOptimalQuality(arg0);
            return result;
        }
    }
    async getQueuedJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueuedJobs();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueuedJobs();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async predictLagRisk(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.predictLagRisk();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.predictLagRisk();
            return result;
        }
    }
    async registerDevice(arg0: DeviceId, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDevice(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDevice(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitJob(arg0: string, arg1: string, arg2: DeviceId | null, arg3: string): Promise<JobId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitJob(arg0, arg1, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitJob(arg0, arg1, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
}
function from_candid_JobStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CachedResult]): CachedResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DeviceId]): DeviceId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobStatus]): JobStatus | null {
    return value.length === 0 ? null : from_candid_JobStatus_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    status: _JobStatus;
    completedAt: [] | [_Time];
    startedAt: [] | [_Time];
    jobType: string;
    submittedAt: _Time;
    results: string;
    error: [] | [string];
    deviceId: [] | [_DeviceId];
    priority: bigint;
    qualityPreset: string;
    payload: string;
}): {
    id: JobId;
    status: JobStatus;
    completedAt?: Time;
    startedAt?: Time;
    jobType: string;
    submittedAt: Time;
    results: string;
    error?: string;
    deviceId?: DeviceId;
    priority: bigint;
    qualityPreset: string;
    payload: string;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n4(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.completedAt)),
        startedAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.startedAt)),
        jobType: value.jobType,
        submittedAt: value.submittedAt,
        results: value.results,
        error: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.error)),
        deviceId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.deviceId)),
        priority: value.priority,
        qualityPreset: value.qualityPreset,
        payload: value.payload
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    completed: null;
} | {
    queued: null;
} | {
    processing: null;
} | {
    failed: null;
}): JobStatus {
    return "cancelled" in value ? JobStatus.cancelled : "completed" in value ? JobStatus.completed : "queued" in value ? JobStatus.queued : "processing" in value ? JobStatus.processing : "failed" in value ? JobStatus.failed : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n7(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeviceId | null): [] | [_DeviceId] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
